name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        ros_distro: [kinetic, melodic, noetic]

    runs-on: ubuntu-latest
    container:
      image: ros:${{matrix.ros_distro}}-ros-base

    steps:
      - uses: actions/checkout@v2

      - name: Create ws
        run: mkdir -p ws/src

      - name: Clone
        run: |
          cd ws/src
          git clone https://github.com/ixblue/ixblue_stdbin_decoder.git
          git clone https://github.com/ixblue/ixblue_ins_stdbin_driver
      
      - name: Install dependencies
        run: |
          cd ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      
      - name: Build WS
        run: cd ws && catkin_make_isolated --install
      
      - name: Test
        run: cd ws && catkin_make_isolated --make-args run_tests
