name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: ROS ${{matrix.ros_distro}} on ${{matrix.distro}}
    if: |
      ${{ (matrix.ros_distro == "kinetic" && matrix.distro == "xenial") ||
          (matrix.ros_distro == "melodic" && matrix.distro == "bionic") ||
          (matrix.ros_distro == "melodic" && matrix.distro == "stretch") ||
          (matrix.ros_distro == "noetic" && matrix.distro == "focal") ||
          (matrix.ros_distro == "noetic" && matrix.distro == "buster")}}
    strategy:
      matrix:
        ros_distro: [kinetic, melodic, noetic]
        distro: [xenial, bionic, focal, stretch, buster]

    runs-on: ubuntu-latest
    container:
      image: ros:${{matrix.ros_distro}}-ros-base-${{matrix.distro}}

    steps:
      - uses: actions/checkout@v2

      - name: Create ws
        run: mkdir -p ws/src

      - name: Clone
        run: |
          cd ws/src
          apt update
          apt install -y git
          git clone https://github.com/ixblue/ixblue_stdbin_decoder.git
          git clone https://github.com/ixblue/ixblue_ins_stdbin_driver
      
      - name: Install dependencies
        run: |
          cd ws
          apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      
      - name: Build WS
        run: |
          cd ws
          . /opt/ros/${{matrix.ros_distro}}/setup.sh
          catkin_make_isolated --install
      
      - name: Test
        run: |
          cd ws
          ls
          . devel_isolated/setup.sh
          catkin_make_isolated --pkg ixblue_ins_driver --install --make-args run_tests
